<?php


namespace App\Models;


class Page extends \TCG\Voyager\Models\Page
{
    protected $undeletable = [
        'home',
        'about',
        'impressum',
        'datenschutz'
    ];

    public function delete()
    {
        if (in_array($this->slug,$this->undeletable)) {
            throw new \Exception('cannot delete those!');
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return $this->body;
    }

}
